export interface SeedFund {
    name: string;
    website: string;
    stage: string;
  }
  
  // VC Funds
  export const vcFunds: SeedFund[] = [
    { name: 'Sequoia Capital', website: 'https://www.sequoiacap.com', stage: 'multi' },
  { name: 'Andreessen Horowitz', website: 'https://a16z.com', stage: 'multi' },
  { name: 'Benchmark', website: 'https://www.benchmark.com', stage: 'early' },
  { name: 'Accel', website: 'https://www.accel.com', stage: 'early' },
  { name: 'Greylock Partners', website: 'https://greylock.com', stage: 'early' },
  { name: 'Kleiner Perkins', website: 'https://www.kleinerperkins.com', stage: 'multi' },
  { name: 'Lightspeed Venture Partners', website: 'https://lsvp.com', stage: 'multi' },
  { name: 'Index Ventures', website: 'https://www.indexventures.com', stage: 'early' },
  { name: 'Founders Fund', website: 'https://foundersfund.com', stage: 'early' },
  { name: 'NEA', website: 'https://www.nea.com', stage: 'multi' },
  { name: 'General Catalyst', website: 'https://www.generalcatalyst.com', stage: 'multi' },
  { name: 'GGV Capital', website: 'https://www.ggvc.com', stage: 'multi' },
  { name: 'Insight Partners', website: 'https://www.insightpartners.com', stage: 'late' },
  { name: 'Tiger Global', website: 'https://www.tigerglobal.com', stage: 'late' },
  { name: 'Coatue', website: 'https://www.coatue.com', stage: 'late' },
  { name: 'Thrive Capital', website: 'https://www.thrivecap.com', stage: 'early' },
  { name: 'Union Square Ventures', website: 'https://www.usv.com', stage: 'early' },
  { name: 'Khosla Ventures', website: 'https://www.khoslaventures.com', stage: 'multi' },
  { name: 'Spark Capital', website: 'https://www.sparkcapital.com', stage: 'early' },
  { name: 'Bessemer Venture Partners', website: 'https://www.bvp.com', stage: 'multi' },
  { name: 'Charles River Ventures', website: 'https://www.crv.com', stage: 'early' },
  { name: '8VC', website: 'https://www.8vc.com', stage: 'multi' },
  { name: 'Lux Capital', website: 'https://www.luxcapital.com', stage: 'early' },
  { name: 'Battery Ventures', website: 'https://www.battery.com', stage: 'multi' },
  { name: 'Redpoint Ventures', website: 'https://www.redpoint.com', stage: 'multi' },
  { name: 'First Round Capital', website: 'https://firstround.com', stage: 'early' },
  { name: 'Initialized Capital', website: 'https://initialized.com', stage: 'early' },
  { name: 'IVP', website: 'https://www.ivp.com', stage: 'multi' },
  { name: 'Menlo Ventures', website: 'https://www.menlovc.com', stage: 'multi' },
  { name: 'Norwest Venture Partners', website: 'https://www.nvp.com', stage: 'multi' },
  { name: 'Felicis Ventures', website: 'https://www.felicis.com', stage: 'multi' },
  { name: 'Ribbit Capital', website: 'https://www.ribbitcap.com', stage: 'multi' },
  { name: 'Iconiq Capital', website: 'https://www.iconiqcapital.com', stage: 'late' },
  { name: 'General Atlantic', website: 'https://www.generalatlantic.com', stage: 'late' },
  { name: 'TCV', website: 'https://www.tcv.com', stage: 'late' },
  { name: 'Summit Partners', website: 'https://www.summitpartners.com', stage: 'late' },
  { name: 'NFX', website: 'https://www.nfx.com', stage: 'early' },
  { name: 'Craft Ventures', website: 'https://www.craftventures.com', stage: 'early' },
  { name: 'ARCH Venture Partners', website: 'https://www.archventure.com', stage: 'early' },
  { name: 'Altos Ventures', website: 'https://www.altos.vc', stage: 'early' },
  { name: 'Forerunner Ventures', website: 'https://www.forerunnerventures.com', stage: 'early' },
  { name: 'B Capital Group', website: 'https://www.bcapgroup.com', stage: 'multi' },
  { name: 'Venrock', website: 'https://www.venrock.com', stage: 'multi' },
  { name: 'Bain Capital Ventures', website: 'https://www.baincapitalventures.com', stage: 'multi' },
  { name: 'Tribe Capital', website: 'https://tribecap.co', stage: 'multi' },
  { name: 'Canaan Partners', website: 'https://www.canaan.com', stage: 'multi' },
  { name: 'Costanoa Ventures', website: 'https://www.costanoavc.com', stage: 'early' },
  { name: 'Notable Capital', website: 'https://www.notablecapital.com', stage: 'multi' },
  { name: 'Madrona Ventures', website: 'https://www.madrona.com', stage: 'early' },
  { name: 'Meritech Capital', website: 'https://www.meritechcapital.com', stage: 'late' },
  { name: 'Greycroft', website: 'https://www.greycroft.com', stage: 'early' },
  { name: 'Foundation Capital', website: 'https://foundationcapital.com', stage: 'early' },
  { name: 'Mayfield Fund', website: 'https://www.mayfield.com', stage: 'multi' },
  { name: 'SignalFire', website: 'https://signalfire.com', stage: 'early' },
  { name: 'Scale Venture Partners', website: 'https://www.scalevp.com', stage: 'multi' },
  { name: 'Blackhorn Ventures', website: 'https://www.blackhornvc.com', stage: 'early' },
  { name: 'True Ventures', website: 'https://trueventures.com', stage: 'early' },
  { name: 'Fifth Wall', website: 'https://fifthwall.com', stage: 'multi' },
  { name: 'Soma Capital', website: 'https://www.somacap.com', stage: 'early' },
  { name: 'HOF Capital', website: 'https://hofcapital.com', stage: 'multi' },
  { name: 'Flybridge', website: 'https://www.flybridge.com', stage: 'early' },
  { name: 'Foothill Ventures', website: 'https://foothill.ventures', stage: 'early' },
  { name: 'Sutter Hill Ventures', website: 'https://www.shv.com', stage: 'early' },
  { name: 'Greenoaks', website: 'https://www.greenoaks.com', stage: 'late' },
  { name: 'Upfront Ventures', website: 'https://www.upfront.com', stage: 'early' },
  { name: 'Kindred Ventures', website: 'https://kindredventures.com', stage: 'early' },
  { name: 'Floodgate', website: 'https://www.floodgate.com', stage: 'early' },
  { name: 'BoxGroup', website: 'https://www.boxgroup.com', stage: 'early' },
  { name: 'BOND', website: 'https://www.bondcap.com', stage: 'late' },
  { name: 'Pear VC', website: 'https://www.pear.vc', stage: 'early' },
  { name: 'Primary Venture Partners', website: 'https://www.primary.vc', stage: 'early' },
  { name: 'Obvious Ventures', website: 'https://obvious.com', stage: 'early' },
  { name: 'Abstract Ventures', website: 'https://www.abstractvc.com/', stage: 'early' },
  { name: 'Susa Ventures', website: 'https://www.susaventures.com/', stage: 'early' },
  { name: 'Neo', website: 'https://neo.com', stage: 'early' },
  ];
  
  // Investment Banks
  export const ibFunds: SeedFund[] = [
    // Bulge Bracket Banks
  { name: 'Goldman Sachs', website: 'https://www.goldmansachs.com', stage: 'bulge bracket' },
  { name: 'Morgan Stanley', website: 'https://www.morganstanley.com', stage: 'bulge bracket' },
  { name: 'J.P. Morgan', website: 'https://www.jpmorgan.com', stage: 'bulge bracket' },
  { name: 'Bank of America', website: 'https://www.bankofamerica.com', stage: 'bulge bracket' },
  { name: 'Citigroup', website: 'https://www.citigroup.com', stage: 'bulge bracket' },
  { name: 'Barclays', website: 'https://www.barclays.com', stage: 'bulge bracket' },
  { name: 'Credit Suisse', website: 'https://www.credit-suisse.com', stage: 'bulge bracket' },
  { name: 'Deutsche Bank', website: 'https://www.db.com', stage: 'bulge bracket' },
  { name: 'UBS', website: 'https://www.ubs.com', stage: 'bulge bracket' },
  { name: 'HSBC', website: 'https://www.hsbc.com', stage: 'bulge bracket' },
  
  // Elite Boutique Banks
  { name: 'Lazard', website: 'https://www.lazard.com', stage: 'elite boutique' },
  { name: 'Evercore', website: 'https://www.evercore.com', stage: 'elite boutique' },
  { name: 'Centerview Partners', website: 'https://www.centerviewpartners.com', stage: 'elite boutique' },
  { name: 'Moelis & Company', website: 'https://www.moelis.com', stage: 'elite boutique' },
  { name: 'Rothschild & Co', website: 'https://www.rothschildandco.com', stage: 'elite boutique' },
  { name: 'PJT Partners', website: 'https://www.pjtpartners.com', stage: 'elite boutique' },
  { name: 'Perella Weinberg Partners', website: 'https://www.pwpartners.com', stage: 'elite boutique' },
  { name: 'Greenhill & Co', website: 'https://www.greenhill.com', stage: 'elite boutique' },
  { name: 'Guggenheim Partners', website: 'https://www.guggenheimpartners.com', stage: 'elite boutique' },
  { name: 'Houlihan Lokey', website: 'https://www.hl.com', stage: 'elite boutique' },
  { name: 'Jefferies', website: 'https://www.jefferies.com', stage: 'elite boutique' },
  { name: 'Qatalyst Partners', website: 'https://www.qatalyst.com', stage: 'elite boutique' },
  { name: 'LionTree Advisors', website: 'https://www.liontree.com', stage: 'elite boutique' },
  { name: 'Allen & Company', website: 'https://alleninvestments.com', stage: 'elite boutique' },
  { name: 'Raine Group', website: 'https://www.raine.com', stage: 'elite boutique' },
  { name: 'Ardea Partners', website: 'https://www.ardeapartners.com', stage: 'elite boutique' },
  
  // Middle Market Banks
  { name: 'William Blair', website: 'https://www.williamblair.com', stage: 'middle market' },
  { name: 'Piper Sandler', website: 'https://www.pipersandler.com', stage: 'middle market' },
  { name: 'Raymond James', website: 'https://www.raymondjames.com', stage: 'middle market' },
  { name: 'Stifel', website: 'https://www.stifel.com', stage: 'middle market' },
  { name: 'Robert W. Baird', website: 'https://www.rwbaird.com', stage: 'middle market' },
  { name: 'Lincoln International', website: 'https://www.lincolninternational.com', stage: 'middle market' },
  { name: 'Harris Williams', website: 'https://www.harriswilliams.com', stage: 'middle market' },
  { name: 'KeyBanc Capital Markets', website: 'https://www.key.com', stage: 'middle market' },
  { name: 'BMO Capital Markets', website: 'https://www.bmo.com', stage: 'middle market' },
  { name: 'Wells Fargo Securities', website: 'https://www.wellsfargo.com', stage: 'middle market' },
  { name: 'RBC Capital Markets', website: 'https://www.rbccm.com', stage: 'middle market' },
  { name: 'Cowen', website: 'https://www.cowen.com', stage: 'middle market' },
  { name: 'Stephens', website: 'https://www.stephens.com', stage: 'middle market' },
  { name: 'Truist Securities', website: 'https://www.truist.com', stage: 'middle market' },
  { name: 'Oppenheimer & Co', website: 'https://www.opco.com', stage: 'middle market' },
  { name: 'Canaccord Genuity', website: 'https://www.canaccordgenuity.com', stage: 'middle market' },
  { name: 'Needham & Company', website: 'https://www.needhamco.com', stage: 'middle market' },
  { name: 'D.A. Davidson', website: 'https://www.dadavidson.com', stage: 'middle market' },
  { name: 'Macquarie Capital', website: 'https://www.macquarie.com', stage: 'middle market' },
  { name: 'Imperial Capital', website: 'https://www.imperialcapital.com', stage: 'middle market' },
  { name: 'Nomura', website: 'https://www.nomura.com', stage: 'middle market' },
  { name: 'Mizuho Financial Group', website: 'https://www.mizuhogroup.com', stage: 'middle market' },
  { name: 'BNP Paribas', website: 'https://group.bnpparibas', stage: 'middle market' },
  { name: 'SMBC Nikko Securities', website: 'https://www.smbcnikko.co.jp/en', stage: 'middle market' },
  { name: 'FT Partners', website: 'https://www.ftpartners.com', stage: 'middle market' },
  { name: 'DC Advisory', website: 'https://www.dcadvisory.com', stage: 'middle market' },
  ];
  
  // Helper function to get seed data based on ranker type
  export function getSeedData(): SeedFund[] {
    const rankerType = process.env.NEXT_PUBLIC_RANKER_TYPE || 'vc';
    return rankerType === 'ib' ? ibFunds : vcFunds;
  }